name: draft
version: git
summary: A tool for developers to create cloud-native applications on Kubernetes. 
description: Draft makes it easier for developers to build applications that run on Kubernetes.
  
adopt-info: draft

grade: stable
confinement: strict

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  draft:
    command: bin/draft
    plugs:
      - home
      - network
      - removable-media

parts:
  draft:
plugin: nil 
    source: https://github.com/Azure/draft.git
    source-type: git
    override-pull: |
       git clone https://github.com/Azure/draft.git src/github.com/Azure/draft
       cd src/github.com/Azure/draft
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/Azure/draft
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/Azure/draft/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/Azure/draft/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/draft
    build-snaps:
      - go
    build-packages:
      - git
      - sed

